server:
  port: 8083

spring:
  application:
    name: task-service
  # No database configuration - using Camunda REST API only

# Camunda REST API configuration only
camunda:
  rest:
    url: ${CAMUNDA_REST_URL:http://camunda:8080/engine-rest}

# Comprehensive Observability Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,httptrace,env,beans
  endpoint:
    health:
      show-details: always
      show-components: always
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        http.server.requests: true
      percentiles:
        http.server.requests: 0.5, 0.95, 0.99
  tracing:
    sampling:
      probability: 1.0  # Sample 100% of traces for better visibility
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans

logging:
  level:
    com.workflow.task: DEBUG
    org.springframework.security: DEBUG
    org.camunda: INFO
    root: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level [traceId=%X{traceId:-},spanId=%X{spanId:-}] %logger{36} - %msg%n"
    stdout: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level [traceId=%X{traceId:-},spanId=%X{spanId:-}] %logger{36} - %msg%n"
    stderr: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level [traceId=%X{traceId:-},spanId=%X{spanId:-}] %logger{36} - %msg%n"
  file:
    name: /app/logs/task-service.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 30
