version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: workflow-postgres
    environment:
      POSTGRES_DB: workflow_db
      POSTGRES_USER: workflow_user
      POSTGRES_PASSWORD: workflow_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - workflow-network

  camunda:
    image: camunda/camunda-bpm-platform:7.21.0
    container_name: workflow-camunda
    environment:
      DB_DRIVER: org.postgresql.Driver
      DB_URL: jdbc:postgresql://postgres:5432/workflow_db
      DB_USERNAME: workflow_user
      DB_PASSWORD: workflow_pass
      WAIT_FOR: postgres:5432
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - workflow-network

  auth-service:
    build:
      context: ./backend/auth-service
      dockerfile: Dockerfile
    container_name: workflow-auth-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/workflow_db
      SPRING_DATASOURCE_USERNAME: workflow_user
      SPRING_DATASOURCE_PASSWORD: workflow_pass
    ports:
      - "8081:8081"
    depends_on:
      - postgres
    networks:
      - workflow-network

  workflow-service:
    build:
      context: ./backend/workflow-service
      dockerfile: Dockerfile
    container_name: workflow-workflow-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/workflow_db
      SPRING_DATASOURCE_USERNAME: workflow_user
      SPRING_DATASOURCE_PASSWORD: workflow_pass
    ports:
      - "8082:8082"
    depends_on:
      - postgres
      - camunda
    networks:
      - workflow-network

  task-service:
    build:
      context: ./backend/task-service
      dockerfile: Dockerfile
    container_name: workflow-task-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/workflow_db
      SPRING_DATASOURCE_USERNAME: workflow_user
      SPRING_DATASOURCE_PASSWORD: workflow_pass
    ports:
      - "8083:8083"
    depends_on:
      - postgres
      - camunda
    networks:
      - workflow-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: workflow-frontend
    environment:
      - REACT_APP_API_BASE_URL=http://auth-service:8081
      - REACT_APP_TASK_SERVICE_URL=http://task-service:8083
      - REACT_APP_WORKFLOW_SERVICE_URL=http://workflow-service:8082
      - REACT_APP_CAMUNDA_URL=http://camunda:8080
    ports:
      - "3000:80"
    depends_on:
      - auth-service
      - workflow-service
      - task-service
    networks:
      - workflow-network

volumes:
  postgres_data:

networks:
  workflow-network:
    driver: bridge
