apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    uid: prometheus
    isDefault: true
    editable: true
  
  - name: Elasticsearch
    type: elasticsearch
    access: proxy
    url: http://elasticsearch:9200
    uid: elasticsearch
    editable: true
    jsonData:
      index: "docker-logs-*"
      timeField: "@timestamp"
      version: 8.11.0
      esVersion: "8.11.0"
      maxConcurrentShardRequests: 256
      includeFrozen: false
      logMessageField: "message"
      logLevelField: ""
  
  - name: Zipkin
    type: zipkin
    access: proxy
    url: http://zipkin:9411
    uid: zipkin
    editable: true
